import { writeFileSync } from 'fs';
import { join } from 'path';
import { createInterface } from 'readline';

const rl = createInterface({
    input: process.stdin,
    output: process.stdout
});

console.log('🚀 Welcome to Matrix Terminal Portfolio Setup!\n');

const questions = [
    {
        key: 'GITHUB_TOKEN',
        question: 'Enter your GitHub Personal Access Token (optional, for higher API rate limits): ',
        required: false
    }
];

async function askQuestion(question) {
    return new Promise((resolve) => {
        rl.question(question.question, (answer) => {
            if (question.required && !answer.trim()) {
                console.log('❌ This field is required. Please try again.\n');
                resolve(askQuestion(question));
            } else {
                resolve(answer.trim());
            }
        });
    });
}

async function setup() {
    const config = {};

    for (const question of questions) {
        const answer = await askQuestion(question);
        if (answer) {
            config[question.key] = answer;
        }
    }
    let envContent = '# Matrix Terminal Portfolio Configuration\n';
    envContent += '# Generated by setup script\n\n';

    for (const [key, value] of Object.entries(config)) {
        envContent += `${key}=${value}\n`;
    }
    const envPath = join(process.cwd(), '.env.local');
    writeFileSync(envPath, envContent);

    console.log('\n✅ Configuration saved to .env.local');
    console.log('\n🎉 Setup complete! You can now run:');
    console.log('   npm run dev');
    console.log('\n📝 Next steps:');
    console.log('   1. Update your personal info in src/data/portfolio.ts');
    console.log('   2. Customize your skills, experience, education, and projects');
    console.log('   3. Deploy to Vercel for production');
    console.log('\n🚀 Happy coding!');

    rl.close();
}

setup().catch(console.error);