const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('🚀 Welcome to Matrix Terminal Portfolio Setup!\n');

const questions = [
  {
    key: 'NEXT_PUBLIC_GITHUB_USERNAME',
    question: 'Enter your GitHub username: ',
    required: true
  },
  {
    key: 'NEXT_PUBLIC_FULL_NAME',
    question: 'Enter your full name: ',
    required: true
  },
  {
    key: 'NEXT_PUBLIC_EMAIL',
    question: 'Enter your email address: ',
    required: true
  },
  {
    key: 'NEXT_PUBLIC_LOCATION',
    question: 'Enter your location (e.g., "San Francisco, CA"): ',
    required: false
  },
  {
    key: 'NEXT_PUBLIC_WEBSITE',
    question: 'Enter your website URL (optional): ',
    required: false
  },
  {
    key: 'NEXT_PUBLIC_LINKEDIN',
    question: 'Enter your LinkedIn URL (optional): ',
    required: false
  },
  {
    key: 'NEXT_PUBLIC_TWITTER',
    question: 'Enter your Twitter URL (optional): ',
    required: false
  },
  {
    key: 'NEXT_PUBLIC_FEATURED_REPOS',
    question: 'Enter your featured repository names (comma-separated): ',
    required: false
  },
  {
    key: 'GITHUB_TOKEN',
    question: 'Enter your GitHub Personal Access Token (optional, for higher rate limits): ',
    required: false
  }
];

async function askQuestion(question) {
  return new Promise((resolve) => {
    rl.question(question.question, (answer) => {
      if (question.required && !answer.trim()) {
        console.log('❌ This field is required. Please try again.\n');
        resolve(askQuestion(question));
      } else {
        resolve(answer.trim());
      }
    });
  });
}

async function setup() {
  const config = {};
  
  for (const question of questions) {
    const answer = await askQuestion(question);
    if (answer) {
      config[question.key] = answer;
    }
  }
  
  // Generate .env.local content
  let envContent = '# Matrix Terminal Portfolio Configuration\n';
  envContent += '# Generated by setup script\n\n';
  
  for (const [key, value] of Object.entries(config)) {
    envContent += `${key}=${value}\n`;
  }
  
  // Write to .env.local
  const envPath = path.join(process.cwd(), '.env.local');
  fs.writeFileSync(envPath, envContent);
  
  console.log('\n✅ Configuration saved to .env.local');
  console.log('\n🎉 Setup complete! You can now run:');
  console.log('   npm run dev');
  console.log('\n📝 Next steps:');
  console.log('   1. Customize your skills in src/app/components/commands/Skills.tsx');
  console.log('   2. Update your timeline in src/app/components/commands/Timeline.tsx');
  console.log('   3. Edit your education in src/app/components/commands/Education.tsx');
  console.log('\n🚀 Happy coding!');
  
  rl.close();
}

setup().catch(console.error);